### PR TITLE
Changed some genrp to celerite

### PR DESCRIPTION
**Pull request by ericagol**
I also ran the asteroseismic python code, which worked well!  Not sure why there are python/genrp/ files included...  I tried pulling the upstream version first.

### CODE REVIEW

**Comment by dfm** [comment]
Please don't merge this!

**Comment by dfm** [comment]
You should revert these commits because you don't want to check these binary files into the repo!

Add "*.o", "__pycache__", etc. to your `.gitignore`.

Also: please don't overwrite the figures! Just do something `git checkout master *.pdf` in the `paper/figures` directory before committing to make sure that the figures don't change.

**Comment by dfm** [comment]
Also, you should delete the `python/genrp` directory.

**Comment by ericagol** [comment]
How do I revert these?

**Pull request closed without merging**
